"""Update model project

Revision ID: 2389c4adbb4e
Revises: 130ecdc08df9
Create Date: 2025-08-13 19:31:23.468630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2389c4adbb4e'
down_revision: Union[str, Sequence[str], None] = '130ecdc08df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
