"""Added role enum to user

Revision ID: cfbbb886464d
Revises: 821b6e917022
Create Date: 2025-08-20 20:25:43.786568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbbb886464d'
down_revision: Union[str, Sequence[str], None] = '821b6e917022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) объявляем enum-объект с правильным именем типа
    user_role = sa.Enum('USER', 'ADMIN', name='user_role_enum')

    # 2) создаём тип в БД, если его ещё нет
    bind = op.get_bind()
    user_role.create(bind, checkfirst=True)

    # 3) добавляем колонку с этим типом (имя колонки делаем нормальным — role)
    op.add_column(
        'users',
        sa.Column('role', user_role, nullable=False, server_default='USER')
    )

    # опционально: убрать server_default после заполнения
    # op.alter_column('users', 'role', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
