"""Create Refresh Token & Modify others

Revision ID: fc5123dd0f2b
Revises: 17c5ba9dd569
Create Date: 2025-08-15 20:27:46.028932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5123dd0f2b'
down_revision: Union[str, Sequence[str], None] = '17c5ba9dd569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
